<?xml version ='1.0' encoding ='UTF-8' ?> 
<definitions name='Results' 
  targetNamespace='http://localhost/WebService1/Results' 
  xmlns:tns=' http://localhost/WebService1/Results ' 
  xmlns:soap='http://schemas.xmlsoap.org/wsdl/soap/' 
  xmlns:xsd='http://www.w3.org/2001/XMLSchema' 
  xmlns:soapenc='http://schemas.xmlsoap.org/soap/encoding/'
  xmlns:wsdl='http://schemas.xmlsoap.org/wsdl/' 
  xmlns='http://schemas.xmlsoap.org/wsdl/'> 
       
<message name='getTeamRequest'> 
  <part name='teamId' type='xsd:string'/> 
</message>  
<message name='getTeamResponse'> 
  <part name='Result' type='xsd:string'/> 
</message> 

<portType name='ResultsPortType'> 
  <operation name='getTeam'> 
    <input message='tns:getTeamRequest'/> 
    <output message='tns:getTeamResponse'/> 
  </operation> 
</portType> 

<binding name='ResultsBinding' type='tns:ResultsPortType'> 
  <soap:binding style='rpc' 
    transport='http://schemas.xmlsoap.org/soap/http'
  /> 
  <operation name='getTeam'> 
    <soap:operation soapAction='urn:localhost-Results#getTeam'/> 
    <input> 
      <soap:body use='encoded' namespace='urn:localhost-Results' 
        encodingStyle='http://schemas.xmlsoap.org/soap/encoding/'/> 
    </input> 
    <output> 
      <soap:body use='encoded' namespace='urn:localhost-Results' 
        encodingStyle='http://schemas.xmlsoap.org/soap/encoding/'/> 
    </output> 
  </operation> 
</binding> 

<service name='ResultsService'> 
  <port name='ResultsPort' binding='ResultsBinding'> 
    <soap:address location='http://localhost/WebService1/soap-server.php'/> 
  </port> 
</service>
</definitions>